//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class afterugdevEntities1 : DbContext
    {
        public afterugdevEntities1()
            : base("name=afterugdevEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AfterUGNotePoints> AfterUGNotePoints { get; set; }
        public virtual DbSet<AfterUGNotePointsTags> AfterUGNotePointsTags { get; set; }
        public virtual DbSet<Attempts> Attempts { get; set; }
        public virtual DbSet<AUGNotes> AUGNotes { get; set; }
        public virtual DbSet<Chapter> Chapter { get; set; }
        public virtual DbSet<Choices> Choices { get; set; }
        public virtual DbSet<DontShowQuestion> DontShowQuestion { get; set; }
        public virtual DbSet<ForgetNotes> ForgetNotes { get; set; }
        public virtual DbSet<GlobalSettings> GlobalSettings { get; set; }
        public virtual DbSet<Hits> Hits { get; set; }
        public virtual DbSet<QuestionDifficulty> QuestionDifficulty { get; set; }
        public virtual DbSet<QuestionsAfterUG> QuestionsAfterUG { get; set; }
        public virtual DbSet<QuestionsAfterUG_Backup> QuestionsAfterUG_Backup { get; set; }
        public virtual DbSet<QuestionTags> QuestionTags { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<TestChild> TestChild { get; set; }
        public virtual DbSet<TestMarkAQuestion> TestMarkAQuestion { get; set; }
        public virtual DbSet<TestMaster> TestMaster { get; set; }
        public virtual DbSet<UserNotes> UserNotes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSettings> UserSettings { get; set; }
    }
}
