//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfterUGNotePointsTags
    {
        public int AfterUGNotePointsTagsID { get; set; }
        public int AfterUGNotePointID { get; set; }
        public int TagID { get; set; }
    
        public virtual AfterUGNotePoints AfterUGNotePoints { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
