//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attempts()
        {
            this.Hits = new HashSet<Hits>();
        }
    
        public long AttemptID { get; set; }
        public int UserID { get; set; }
        public int QuestionID { get; set; }
        public int AttemptNumber { get; set; }
        public string TestOrStudySession { get; set; }
        public long TimeTaken { get; set; }
        public long UserFinalHitAnswer { get; set; }
        public int AnswerStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hits> Hits { get; set; }
        public virtual QuestionsAfterUG QuestionsAfterUG { get; set; }
        public virtual Users Users { get; set; }
    }
}
