//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUGNotes
    {
        public int AUGNotesID { get; set; }
        public int QuestionID { get; set; }
        public string AUGNotePointText { get; set; }
        public int AUGNotesAddedByEmployeeUserID { get; set; }
        public int AUGNotesApprovedByEmployeeUserID { get; set; }
        public bool IsToBeDisplayed { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual QuestionsAfterUG QuestionsAfterUG { get; set; }
    }
}
