//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgetNotes
    {
        public long ForgetNotesID { get; set; }
        public int UserWhoWantsToForgetNotesID { get; set; }
        public int QuestionID { get; set; }
        public int UserAfterUGNotesID { get; set; }
        public Nullable<bool> ForgetStatus { get; set; }
    
        public virtual QuestionsAfterUG QuestionsAfterUG { get; set; }
        public virtual UserAfterUGNotes UserAfterUGNotes { get; set; }
        public virtual Users Users { get; set; }
    }
}
