//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSettings
    {
        public int GlobalSettingsID { get; set; }
        public int NoOfQuestionsPerTest { get; set; }
        public int NoOfChoicesPerQuestion { get; set; }
        public int NoOfRepetitionsCorrect { get; set; }
        public int NoOfRepetitionsIncorrect { get; set; }
    }
}
