//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hits
    {
        public long HitID { get; set; }
        public long AttemptID { get; set; }
        public byte WhichNoOfHit { get; set; }
        public Nullable<long> UserAnswerForTheHit { get; set; }
    
        public virtual Attempts Attempts { get; set; }
    }
}
