//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsAfterUG_Backup
    {
        public int QuestionID { get; set; }
        public byte QuestionType { get; set; }
        public string Question { get; set; }
        public bool IsQuestionReviewed { get; set; }
        public bool IsQuestionSpinned { get; set; }
    }
}
