//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsAfterUG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionsAfterUG()
        {
            this.Attempts = new HashSet<Attempts>();
            this.Choices = new HashSet<Choices>();
            this.ForgetNotes = new HashSet<ForgetNotes>();
            this.QuestionTags = new HashSet<QuestionTags>();
            this.UserAfterUGNotes = new HashSet<UserAfterUGNotes>();
            this.UserNotes = new HashSet<UserNotes>();
            this.TestMarkAQuestion = new HashSet<TestMarkAQuestion>();
            this.TestChild = new HashSet<TestChild>();
        }
    
        public int QuestionID { get; set; }
        public byte QuestionType { get; set; }
        public string Question { get; set; }
        public bool IsQuestionReviewed { get; set; }
        public bool IsQuestionSpinned { get; set; }
        public bool IsCorrectChoiceVerified { get; set; }
        public long CorrectChoiceID { get; set; }
        public Nullable<int> ChapterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attempts> Attempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Choices> Choices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForgetNotes> ForgetNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionTags> QuestionTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAfterUGNotes> UserAfterUGNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotes> UserNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestMarkAQuestion> TestMarkAQuestion { get; set; }
        public virtual Chapter Chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestChild> TestChild { get; set; }
    }
}
