//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestMaster
    {
        public int TestID { get; set; }
        public int UserID { get; set; }
        public bool IsTestComplete { get; set; }
        public bool IsTestOrStudySession { get; set; }
        public bool IsReview { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
