//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afterug.core.middlelayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSettings
    {
        public int UserSettingsID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> NoOfQuestionsPerTest { get; set; }
        public Nullable<int> NoOfChoicesPerQuestion { get; set; }
        public Nullable<int> NoOfRepetitionsCorrect { get; set; }
        public Nullable<int> NoOfRepetitionsIncorrect { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
