//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminsitedev
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Question
    {
        public int QuestionID { get; set; }
        public byte QuestionType { get; set; }
        [UIHint("tinymce_jquery_full"), AllowHtml]
        [Required]
        public string QuestionOriginal { get; set; }
        [Required]
        public string ChoiceAOriginal { get; set; }
        [Required]
        public string ChoiceBOriginal { get; set; }
        [Required]
        public string ChoiceCOriginal { get; set; }
        [Required]
        public string ChoiceDOriginal { get; set; }
        [Required]
        public string CorrectChoiceOriginal { get; set; }
        [Required]
        public string QuestionMainCategory { get; set; }
        public string QuestionSubCategory { get; set; }
        [Required]
        public bool IsPreviousYearExamQuestion { get; set; }
        [Required]
        public string WhichExam { get; set; }
        [Required]
        public int WhichYear { get; set; }
        public string QuestionSpinned { get; set; }
        public string ChoiceASpinned { get; set; }
        public string ChoiceBSpinned { get; set; }
        public string ChoiceCSpinned { get; set; }
        public string ChoiceDSpinned { get; set; }
        public string CorrectChoiceSpinned { get; set; }
        public string ErrorsSpinned { get; set; }
        public string JustificationsFinal { get; set; }
        public string ReviewComments { get; set; }
        public string ResponseReviewComments { get; set; }
        public string QuestionFinal { get; set; }
        public string ChoiceAFinal { get; set; }
        public string ChoiceBFinal { get; set; }
        public string ChoiceCFinal { get; set; }
        public string ChoiceDFinal { get; set; }
        public string CorrectChoiceFinal { get; set; }
        public string QuestionLive { get; set; }
        public string ChoiceALive { get; set; }
        public string ChoiceBLive { get; set; }
        public string ChoiceCLive { get; set; }
        public string ChoiceDLive { get; set; }
        public string CorrectChoiceLive { get; set; }
        public Nullable<bool> IsCorrectChoiceVerified { get; set; }
        public Nullable<bool> IsQuestionSpinned { get; set; }
        public Nullable<bool> IsFinalReviewCompleted { get; set; }
        public Nullable<bool> IsPeerCrossReviewCompleted { get; set; }
        public Nullable<bool> IsQuestionReadyForLive { get; set; }
        [Required]
        public Nullable<int> BookPageNumber { get; set; }
        [Required]
        public Nullable<int> BookQuestionNumber { get; set; }
        [Required]
        public Nullable<int> OurQuestionNumber { get; set; }
    }
}
